=== firewut/data-pipelines-worker/config/pipelines_validation_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$defs": {
        "slug": {
            "type": "string",
            "pattern": "^[-\\w]+$"
        },
        "block": {
            "type": "object",
            "properties": {
                "id": {
                    "$ref": "#/$defs/slug"
                },
                "slug": {
                    "$ref": "#/$defs/slug"
                },
                "description": {
                    "type": "string",
                    "minLength": 20
                },
                "output_config": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": ["array", "number", "string", "boolean"]
                        }
                    },
                    "additionalProperties": true,
                    "required": ["type"]
                }
            },
            "anyOf": [
                {
                    "properties": {
                        "input_config": {
                            "type": "object",
                            "properties": {
                                "property": {
                                    "type": "object",
                                    "patternProperties": {
                                        "^.*$": {
                                            "type": "object",
                                            "properties": {
                                                "origin": {
                                                    "type": "string"
                                                },
                                                "xpath": {
                                                    "type": "string"
                                                }
                                            },
                                            "additionalProperties": true,
                                            "required": ["origin"]
                                        }
                                    }
                                },
                                "type": {
                                    "type": "string",
                                    "enum": ["array", "number", "string", "boolean"]
                                },
                                "parallel": {
                                    "type": "boolean",
                                    "default": false
                                },
                                "format_vars": {
                                    "type": "object",
                                    "patternProperties": {
                                        "^.*$": {
                                            "type": "object",
                                            "properties": {
                                                "origin": {
                                                    "type": "string"
                                                },
                                                "xpath": {
                                                    "type": "string"
                                                }
                                            },
                                            "additionalProperties": true,
                                            "required": ["origin"]
                                        }
                                    }
                                }
                            },
                            "additionalProperties": true,
                            "required": ["property"]
                        }
                    },
                    "required": ["input_config"]
                },
                {
                    "properties": {
                        "input": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "required": ["input"]
                }
            ],
            "required": [
                "id",
                "slug",
                "description"
            ]
        }
    },
    "type": "object",
    "properties": {
        "slug": {
            "$ref": "#/$defs/slug"
        },
        "title": {
            "type": "string",
            "minLength": 10
        },
        "description": {
            "type": "string",
            "minLength": 20
        },
        "blocks": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/$defs/block"
            }
        }
    },
    "required": [
        "slug",
        "title",
        "description",
        "blocks"
    ],
    "additionalProperties": false
}

=== firewut/data-pipelines-worker/config/pipelines/openai-subtitles-from-media.json
{
    "slug": "openai-subtitles-from-video",
    "title": "Add subtitles to video",
    "description": "Generates subtitles for video using OpenAI API",
    "blocks": [
        {
            "id": "audio_from_video",
            "slug": "get-audio-from-video",
            "description": "Extract audio from video",
            "input": {
            }
        },
        {
            "id": "openai_transcription_request",
            "slug": "get-audio-transcription",
            "description": "Make a request to OpenAI TTS API to convert audio to transcription",
            "input_config": {
                "property": {
                    "audio_file": {
                        "origin": "get-audio-from-video"
                    }
                }
            }
        },
        {
            "id": "subtitles_from_transcription",
            "slug": "make-video-subtitle-file",
            "description": "Create a subtitle file from the transcription",
            "input_config": {
                "property": {
                    "transcription": {
                        "origin": "get-audio-transcription"
                    }
                }
            },
            "input": {
                "input_format": "openai_verbose_json",
                "output_format": "ass"
            }
        }
    ]
}

=== firewut/data-pipelines-worker/config/pipelines/openai-mux-subtitles-to-video.json
{
    "slug": "openai-mux-subtitles-to-video",
    "title": "Mux subtitles to video",
    "description": "Generates subtitles for video using OpenAI API",
    "blocks": [
        {
            "id": "upload_file",
            "slug": "upload-video-file",
            "description": "Upload a video for further processing",
            "input": {}
        },
        {
            "id": "audio_from_video",
            "slug": "get-audio-from-video",
            "description": "Extract audio from video",
            "input_config": {
                "property": {
                    "video": {
                        "origin": "upload-video-file"
                    }
                }
            }
        },
        {
            "id": "openai_transcription_request",
            "slug": "get-audio-transcription",
            "description": "Make a request to OpenAI TTS API to convert audio to transcription",
            "input_config": {
                "property": {
                    "audio": {
                        "origin": "get-audio-from-video"
                    }
                }
            }
        },
        {
            "id": "subtitles_from_transcription",
            "slug": "make-video-subtitles-file",
            "description": "Create a subtitles file from the transcription",
            "input_config": {
                "property": {
                    "transcription": {
                        "origin": "get-audio-transcription"
                    }
                }
            },
            "input": {
                "input_format": "openai_verbose_json",
                "output_format": "ass"
            }
        },
        {
            "id": "video_add_subtitles",
            "slug": "mux-subtitles-to-video",
            "description": "Add subtitles to video in a separate track ( non destructive )",
            "input_config": {
                "property": {
                    "video": {
                        "origin": "upload-video-file"
                    },
                    "subtitles": {
                        "origin": "make-video-subtitles-file"
                    }
                }
            },
            "input": {
                "embedding_type": "mux"
            }
        }
    ]
}

=== firewut/data-pipelines-worker/config/pipelines/openai-test.json
{
    "slug": "openai-test",
    "title": "Youtube video generation pipeline from prompt",
    "description": "Generates videos for youtube Channel <CHANNEL>. Uses Prompt in the Block.",
    "blocks": [
        {
            "id": "openai_chat_completion",
            "slug": "get-event-text",
            "description": "Get a text from OpenAI Chat Completion API",
            "input": {
                "model": "gpt-4o-2024-08-06",
                "system_prompt": "You must look for Historical event ( use google ) which happened today years ago. Write a short story about it. Add some interesting facts and make it engaging. The story MUST BE 30 words long!!!!!!!!",
                "user_prompt": "What happened years ago at date October 5 ?"
            }
        },
        {
            "id": "send_moderation_telegram",
            "slug": "send-event-text-moderation-to-telegram",
            "description": "Send the Event Text to Telegram for moderation",
            "input_config": {
                "property": {
                    "text": {
                        "origin": "get-event-text",
                        "jsonPath": "$"
                    }
                }
            },
            "input": {
                "group_id": -4573786981
            }
        },
        {
            "id": "fetch_moderation_telegram",
            "slug": "fetch-event-text-moderation-from-telegram",
            "description": "Fetch the Event Text moderation decision from Telegram",
            "input": {
                "block_slug": "send-event-text-moderation-to-telegram"
            }
        },
        {
            "id": "openai_tts_request",
            "slug": "get-event-tts",
            "description": "Make a request to OpenAI TTS API to convert text to speech",
            "input_config": {
                "property": {
                    "text": {
                        "origin": "get-event-text",
                        "jsonPath": "$"
                    }
                }
            }
        },
        {
            "id": "openai_transcription_request",
            "slug": "get-event-transcription",
            "description": "Make a request to OpenAI TTS API to convert text to speech",
            "input_config": {
                "property": {
                    "audio_file": {
                        "origin": "get-event-tts"
                    }
                }
            }
        },
        {
            "id": "text_add_prefix_suffix",
            "slug": "make-system-prompt-for-image-prompt-generation",
            "description": "Make a system prompt for image generation from the event text",
            "input_config": {
                "property": {
                    "text": {
                        "origin": "get-event-transcription",
                        "jsonPath": "$.text"
                    }
                }
            },
            "input": {
                "prefix": "You are going to create a prompt to generate an image according to this text and user request: "
            }
        },
        {
            "id": "openai_chat_completion",
            "slug": "get-prompt-for-image-generation-text",
            "description": "Get prompts for image generation from OpenAI Chat Completion",
            "input_config": {
                "type": "array",
                "property": {
                    "system_prompt": {
                        "origin": "make-system-prompt-for-image-prompt-generation"
                    },
                    "user_prompt": {
                        "origin": "get-event-transcription",
                        "jsonPath": "$.segments[*].text"
                    }
                }
            },
            "input": {
                "model": "gpt-4o-2024-08-06"
            }
        },
        {
            "id": "openai_image_request",
            "slug": "get-event-images",
            "description": "Make a request to OpenAI Image API to get an image",
            "input_config": {
                "type": "array",
                "property": {
                    "prompt": {
                        "origin": "get-prompt-for-image-generation-text"
                    }
                }
            },
            "input": {
                "quality": "hd",
                "size": "1024x1792"
            }
        },
        {
            "id": "send_moderation_telegram",
            "slug": "send-event-images-moderation-to-telegram",
            "description": "Send generated Event Images to Telegram for moderation",
            "input_config": {
                "type": "array",
                "parallel": true,
                "property": {
                    "image": {
                        "origin": "get-event-images"
                    },
                    "text": {
                        "origin": "get-event-transcription",
                        "jsonPath": "$.segments[*].text"
                    }
                }
            },
            "input": {
                "group_id": -4573786981,
                "extra_decisions": {
                    "Regenerate": "Refresh"
                }
            }
        },
        {
            "id": "fetch_moderation_telegram",
            "slug": "fetch-event-images-moderation-from-telegram",
            "description": "Fetch the moderation Image decision from Telegram",
            "input_config": {
                "type": "array"
            },
            "input": {
                "block_slug": "send-event-images-moderation-to-telegram"
            }
        }
    ]
}

=== firewut/data-pipelines-worker/config/pipelines/test-two-http-blocks.json
{
    "slug": "test-two-http-blocks",
    "title": "Test two HTTP Blocks",
    "description": "First Block makes a request to a URL and the second block makes a request result of First Block",
    "blocks": [
        {
            "id": "http_request",
            "slug": "test-block-first-slug",
            "description": "Request Local Resourse",
            "input": {
                "url": "http://localhost:3000"
            }
        },
        {
            "id": "http_request",
            "slug": "test-block-second-slug",
            "description": "Request Result from First Block",
            "input_config": {
                "property": {
                    "url": {
                        "origin": "test-block-first-slug"
                    }
                }
            }
        }
    ]
}

=== firewut/data-pipelines-worker/config/pipelines/openai-podcast-summary.json
{
    "slug": "openai-podcast-summary",
    "title": "Make a summary of a podcast",
    "description": "Make a summary of a podcast using OpenAI API",
    "blocks": [
        {
            "id": "openai_transcription_request",
            "slug": "get-event-transcription",
            "description": "Make a request to OpenAI TTS API to convert audio to transcription",
            "input": {
                "format": "text"
            }
        },
        {
            "id": "openai_chat_completion",
            "slug": "get-summary-of-a-podcast",
            "description": "Gets summary of a podcast from OpenAI Chat Completion",
            "input_config": {
                "property": {
                    "user_prompt": {
                        "origin": "get-event-transcription",
                        "json_path": "$.text"
                    }
                }
            },
            "input": {
                "model": "gpt-4o-2024-08-06",
                "system_prompt": "Please summarize the following podcast episode transcript in a concise and engaging way, highlighting the key topics, themes, and insights discussed. The summary should be approximately 200 words long and suitable for use as a description on podcast platforms. Avoid technical jargon unless necessary and ensure the tone is professional yet accessible."
            }
        }
    ]
}
